INSERT INTO dbo.Member
VALUES
  ('Adrian Dick',1,NULL,0,NULL)
, ('Brent Verry',0,NULL,0,NULL)
, ('Brent Gladding',0,NULL,0,NULL)
, ('Matt Moore',1,NULL,0,NULL)
, ('Jason Mann',0,NULL,0,NULL)
, ('Damian Coventry',0,NULL,0,NULL)
, ('Martin Dick',0,NULL,0,NULL)
, ('Justin MacLennan',0,NULL,0,NULL)
, ('Dave Fowlie',1,NULL,0,NULL)
, ('Francis Lings',1,NULL,0,NULL)
, ('Chris Whitehead',0,NULL,0,NULL)
, ('Rob MacLennan',1,NULL,0,NULL)
, ('Kurt Kelsall',0,NULL,0,NULL)
, ('Matt Wilson-Vogler',0,NULL,0,NULL)
, ('Stu Macferson',0,NULL,0,NULL)
, ('Philip Hunt',0,NULL,0,NULL)
, ('Ken Nicod',0,NULL,0,NULL)
, ('Scott Robinson',0,NULL,1,'Expelled due to non-attendance')
, ('Kenny Stuart',0,NULL,0,NULL)
, ('Jason Armstrong',0,NULL,1,'Expelled due to non-attendance')
, ('Greg Long',0,NULL,0,NULL)
, ('Chris Stephens',0,NULL,0,NULL)
, ('Gary Spalding',0,NULL,0,NULL)
, ('Kareem Kader',0,NULL,1,'Expelled due to non-attendance')
, ('Hamish Graham',0,NULL,1,'Expelled due to non-attendance')
, ('Elvin Maharaj',0,NULL,0,NULL)
, ('Daryl Blake',0,NULL,0,NULL)
, ('Paul James',0,NULL,0,NULL)
, ('Davey Goode',0,NULL,0,NULL)
, ('Peter Wakely',0,NULL,0,NULL)
, ('Brett Jones',0,NULL,0,NULL)
, ('Mark George',0,NULL,0,NULL)
, ('Aj Ay',0,NULL,0,NULL)
, ('Kevin Barnard',0,NULL,0,NULL)
, ('Francis Payapaya',0,NULL,0,NULL)
, ('Chris Van Poppel',0,NULL,0,NULL)
, ('Vincent Dick',0,NULL,0,NULL)
